language: python
python:
  - "2.7"
# Need to set this so that packages installed with apt-get are available

virtualenv:
  system_site_packages: true
env:
  - OMP_NUM_THREADS=4
before_install:
  - sudo apt update
  - sudo apt install gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install pip python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib astropy nose pyqt
  - pip install -q coverage coveralls
install:
  - python setup.py install
script:
    # Run nosetests as a dry-run. A real run will not work because there is no 
    # IDL installed under Travis. Thus, to not run it, we added the --collect-only
    # argument. When the IDL dependcy is removed, take out this argument.
  - nosetests s4 tests -v --with-doctest --with-coverage --cover-package=s4 --collect-only
notifications:
  email: false
